services:
  mongo:
    image: mongo:8.2.12
    container_name: titleregistration-mongo
    network_mode: bridge
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: titleregistration
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:password}
    volumes:
      - titleregistration-mongo-data:/data/db
volumes:
  titleregistration-mongo-data:
