services:
  mongo:
    image: mongo:8.2.12
    container_name: mongo-titleregistration
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: titleregistration
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
    volumes:
      - titleregistration-mongo-data:/data/db
    networks:
      - titleregistration-network

volumes:
  titleregistration-mongo-data:

networks:
  titleregistration-network:
    driver: bridge
